sdk:
  - changed-files:
      - any-glob-to-any-file: packages/sdk/**/*

hono:
  - changed-files:
      - any-glob-to-any-file: packages/hono/**/*

express:
  - changed-files:
      - any-glob-to-any-file: packages/express/**/*

next:
  - changed-files:
      - any-glob-to-any-file: packages/next/**/*

react:
  - changed-files:
      - any-glob-to-any-file: packages/react/**/*

cli:
  - changed-files:
      - any-glob-to-any-file: packages/cli/**/*

create-app:
  - changed-files:
      - any-glob-to-any-file: packages/create-app/**/*

mcp:
  - changed-files:
      - any-glob-to-any-file: packages/mcp/**/*

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - packages/sdk/README.md
          - "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file: pnpm-lock.yaml

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
